### PR TITLE
Add environment, binder, readme with direct link to lab 

### PR DESCRIPTION
**Pull request by bollwyvl**
This adds an `environment.yml` and verified activation with the current conda-forge jupyterlab. Slick! 🐧

### CODE REVIEW

**Comment by blink1073** [comment]
Sorry, merge conflict (I added a README).

**Comment by bollwyvl** [comment]
🔨

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
Binder is failing.

**Comment by bollwyvl** [comment]
Build is running now....

**Comment by bollwyvl** [comment]
http://mybinder.org/status/jupyterday-atlanta-2016/jupyterlab-walkthrough

**Comment by blink1073** [comment]
Oh, ha, assuming that works I will reinstate.

**Comment by bollwyvl** [comment]
Yerp, just tested this:
http://mybinder.org/repo/jupyterday-atlanta-2016/jupyterlab-walkthrough/lab

looks good!

**Comment by blink1073** [comment]
Freaking awesome!

**Pull request merged**
